spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/tracker
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: tracker
